version: 2
linters:
  default: all
  disable:
  - cyclop # max 10 is a bit too low imo. Maybe increase the limit and enable eventually
  - depguard # Maintaining the depguard rules is tedious
  - err113 # Eh, dynamic errors aren't the end of the world
  - exhaustruct # Disagree that you should be setting _every_ struct field
  - forbidigo # This is a CLI application. We're going to print things!
  - funlen # 60 lines feels too restrictive as a limit on function length
  - godox # TODO is fine. shush
  - ireturn # I disagree with this
  - revive # To strict about comment structure
  - varnamelen # I don't mind single letter names
  - wrapcheck # Wrapping all external errors is tedious
  - wsl # Deprecated and conflicts with wsl_5
formatters:
  enable:
  - gofmt
  - goimports
  - golines

