version: '3'

vars:
  BACKEND_DIR: .
  CLIENT_DIR: ./client

tasks:
  # Development tasks
  dev:
    desc: Start backend and client development servers
    deps: [proto:gen]
    cmds:
      - task: backend:dev &
      - task: client:dev

  # Proto generation
  proto:gen:
    desc: Generate code from protos
    cmds:
      - buf generate
    sources:
      - proto/**/*.proto
    generates:
      - gen/**/*.go
      - client/gen/**/*.ts

  # Backend tasks
  backend:dev:
    desc: Start backend development server
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go run . serve

  backend:build:
    desc: Build backend binary
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go build -o bin/byte .

  # Client tasks
  client:dev:
    desc: Start Expo development server
    dir: "{{.CLIENT_DIR}}"
    cmds:
      - npm start

  client:web:
    desc: Start Expo web development
    dir: "{{.CLIENT_DIR}}"
    cmds:
      - npm run web

  client:ios:
    desc: Start iOS development
    dir: "{{.CLIENT_DIR}}"
    cmds:
      - npm run ios

  client:android:
    desc: Start Android development
    dir: "{{.CLIENT_DIR}}"
    cmds:
      - npm run android

  # Setup tasks
  setup:
    desc: Setup development environment
    cmds:
      - task: backend:deps
      - task: client:deps

  backend:deps:
    desc: Install backend dependencies
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go mod download

  client:deps:
    desc: Install client dependencies
    dir: "{{.CLIENT_DIR}}"
    cmds:
      - npm install

  # Build tasks
  build:
    desc: Build all platforms
    deps: [proto:gen]
    cmds:
      - task: backend:build
      - task: client:build

  client:build:
    desc: Build client for production
    dir: "{{.CLIENT_DIR}}"
    cmds:
      - npm run build

  # Clean tasks
  clean:
    desc: Clean generated files and dependencies
    cmds:
      - rm -rf gen/
      - rm -rf client/gen/
      - rm -rf client/node_modules/
      - rm -rf bin/