name: lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4

  swiftlint:
    name: Swift Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint lint --strict --reporter github-actions-logging

  swift-format:
    name: Swift Format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install swift-format
        run: brew install swift-format

      - name: Check Swift formatting
        run: |
          # Check all Swift files in ios and swift directories
          find ios swift -name "*.swift" \
            -not -path "*/Generated/*" \
            -not -path "*/GeneratedMocks/*" \
            -not -path "*/.build/*" \
            -not -path "*/Pods/*" \
            -print0 | xargs -0 swift-format lint --strict --parallel
